{% set name = "super_collections" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94c1ec96c0a0d5e8e7d389ed8cde6882ac246940507c5e6b86e91945c2968d46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
  run:
    - python >=3.8
    - hjson-py

test:
  imports:
    - super_collections
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: super_collections
  - name: super-collections
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("super_collections", max_pin="x.x.x") }}
        - python >=3.8
    test:
      imports:
        - super_collections

about:
  home: https://github.com/fralau/super-collections
  summary: 'Dictionaries as you dreamed them when you were a kid.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
